import type { Column, Task } from "@/types/task";

export const initialColumns: Column[] = [
	{ name: "Todo", order: 0 },
	{ name: "In Progress", order: 1 },
	{ name: "Done", order: 2 },
];

export const initialTasks: Task[] = [
	{
		id: "task-1",
		title: "ログイン画面のバグ修正",
		status: "Todo",
		priority: "High",
		labels: ["bug", "frontend"],
		parent: undefined,
		links: ["tasks/search-feature.md"],
		children: ["tasks/login-ui-fix.md"],
		reverseLinks: [],
		body: "ログイン画面でエラーメッセージが表示されない問題を修正する。",
		filePath: "tasks/fix-login-bug.md",
	},
	{
		id: "task-2",
		title: "検索機能の追加",
		status: "In Progress",
		priority: "Medium",
		labels: ["feature", "frontend"],
		parent: undefined,
		links: [],
		children: [],
		reverseLinks: ["tasks/fix-login-bug.md"],
		body: "商品一覧ページにキーワード検索機能を追加する。\n\n## 受け入れ基準\n\n- キーワード入力で部分一致検索できる\n- 検索結果が0件の場合メッセージを表示する",
		filePath: "tasks/search-feature.md",
	},
	{
		id: "task-3",
		title: "ログインUIの修正",
		status: "Todo",
		priority: "Low",
		labels: ["frontend"],
		parent: "tasks/fix-login-bug.md",
		links: [],
		children: [],
		reverseLinks: [],
		body: "ログインフォームのレイアウトを調整する。",
		filePath: "tasks/login-ui-fix.md",
	},
	{
		id: "task-4",
		title: "READMEの更新",
		status: "Done",
		labels: ["docs"],
		parent: undefined,
		links: ["tasks/search-feature.md"],
		children: [],
		reverseLinks: [],
		body: "プロジェクトのREADMEを最新の仕様に合わせて更新する。",
		filePath: "tasks/update-readme.md",
	},
	{
		id: "task-5",
		title: "API エンドポイントの設計",
		status: "In Progress",
		priority: "High",
		labels: ["backend", "design"],
		parent: undefined,
		links: [],
		children: [],
		reverseLinks: [],
		body: "RESTful API のエンドポイント設計を行う。",
		filePath: "tasks/api-design.md",
	},
];
